extern crate num;
extern crate project_euler_rust;

use project_euler_rust::factors::prime_factors::prime_factors;
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
#[test]
fn pe_3_13195_yields_29() {
    let prime_factors_13195 = prime_factors(13195);
    assert_eq!(prime_factors_13195, vec![5, 7, 13, 29]);
}
#[test]
fn pe_3_600851475143_yields_6857() {
    assert_eq!(
        prime_factors(600_851_475_143u128),
        vec![71, 839, 1471, 6857]
    );
}
